services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: futeccons-shop
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d futeccons-shop"]
      interval: 5s
      timeout: 5s
      retries: 5
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      DB_USER: admin
      DB_HOST: db
      DB_NAME: futeccons-shop
      DB_PASSWORD: admin
      DATABASE_URL: postgresql://admin:admin@db:5432/futeccons-shop
      NODE_ENV: development
    command: sh run.sh
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data:
